In [ ]:
import numpy as np
import pandas as pd
from google.colab import files

In [ ]:
F = files.upload()

In [ ]:
df = pd.read_csv('/content/dermatology_database_1.csv')
df.head(36)

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,Class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3
5,2,3,2,0,0,0,0,0,0,0,...,0,0,2,0,0,0,1,0,41,2
6,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,18,5
7,2,2,3,3,3,3,0,2,0,0,...,2,2,3,2,0,0,3,3,57,3
8,2,2,1,0,2,0,0,0,0,0,...,0,0,2,0,0,0,2,0,22,4
9,2,2,1,0,1,0,0,0,0,0,...,0,0,2,0,0,0,2,0,30,4
10,3,3,2,1,1,0,0,0,2,2,...,0,0,0,0,0,0,1,0,20,1
11,2,2,0,3,0,0,0,0,0,0,...,0,0,3,0,0,0,1,0,21,2
12,3,3,1,2,0,0,0,0,0,1,...,0,0,2,0,0,0,1,0,22,2
13,2,3,3,0,0,0,0,0,1,1,...,0,0,0,0,0,0,2,0,10,1
14,2,2,3,3,0,3,0,2,0,0,...,0,3,0,3,0,0,1,3,65,3
15,1,1,0,1,3,0,0,0,0,0,...,0,0,2,0,0,0,2,0,40,4
16,2,2,1,3,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,30,2
17,3,3,3,0,0,0,0,0,3,3,...,3,0,0,0,0,0,2,0,38,1
18,2,1,3,3,3,3,0,0,2,0,...,0,2,0,3,0,0,2,3,23,3
19,1,1,0,3,0,0,0,0,0,0,...,0,0,1,0,0,0,2,0,17,5
20,2,1,1,2,0,0,3,0,1,2,...,0,0,0,0,1,2,1,0,8,6
21,3,2,2,0,0,0,0,0,0,0,...,0,0,3,0,0,0,2,0,51,2
22,2,2,0,2,0,0,0,0,0,0,...,0,0,1,0,1,0,2,0,42,5
23,2,2,2,3,2,2,0,2,0,0,...,0,3,0,2,0,0,2,3,44,3
24,2,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,22,5
25,2,1,1,0,1,0,0,0,2,0,...,2,0,0,0,0,0,2,0,33,1
26,1,1,0,1,0,0,3,0,1,0,...,0,0,1,0,2,2,1,0,10,6
27,1,2,2,3,0,0,0,0,0,0,...,0,0,1,0,0,0,3,0,17,5
28,3,2,2,2,0,0,0,0,0,0,...,0,0,2,0,1,1,2,0,43,2
29,1,1,2,3,2,2,0,3,0,0,...,0,3,0,3,1,0,2,3,50,3
30,3,2,1,2,0,0,0,0,1,2,...,2,0,0,0,0,0,1,0,50,1
31,3,2,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,10,2
32,2,3,3,3,3,0,0,0,3,3,...,0,0,0,0,0,0,1,0,34,1
33,2,2,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,36,1
34,2,1,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,36,4
35,2,2,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,36,2

In [ ]:
df.shape

(366, 35)

In [ ]:
df['Class'].unique()

NameError: name 'df' is not defined

In [ ]:
mu = np.mean(df['Class'])
mu

2.80327868852459

In [ ]:
df.replace({'?': 36, 'NaN': 36},inplace = True)
df.loc[263]

erythema                                1
scaling                                 1
definite_borders                        1
itching                                 3
koebner_phenomenon                      0
polygonal_papules                       0
follicular_papules                      0
oral_mucosal_involvement                0
knee_and_elbow_involvement              0
scalp_involvement                       0
family_history                          0
melanin_incontinence                    0
eosinophils_infiltrate                  0
PNL_infiltrate                          0
fibrosis_papillary_dermis               3
exocytosis                              2
acanthosis                              3
hyperkeratosis                          1
parakeratosis                           2
clubbing_rete_ridges                    2
elongation_rete_ridges                  2
thinning_suprapapillary_epidermis       0
spongiform_pustule                      0
munro_microabcess                       0
focal_hypergranulosis                   0
disappearance_granular_layer            0
vacuolisation_damage_basal_layer        0
spongiosis                              3
saw_tooth_appearance_retes              0
follicular_horn_plug                    0
perifollicular_parakeratosis            0
inflammatory_mononuclear_infiltrate     2
band_like_infiltrate                    0
age                                    36
Class                                   5
Name: 263, dtype: int64

In [ ]:
mu = df.age.mean()
mu

36.2896174863388

In [ ]:
sigma =df.age.std()

In [ ]:
df['age' ] = (df['age'] - mu)/sigma

In [ ]:
df.age.mean()

-3.8827471899459027e-17

In [ ]:
#df['xo'] = 1
df.head()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,Class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,1.234540,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,-1.866593,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,-0.678925,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,0.244817,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,0.574725,3

In [ ]:
df.age.std()

1.0

In [ ]:
x = df.drop(['Class'], axis= 1)
y = df.iloc[:,34]
x

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,focal_hypergranulosis,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age
0,2,2,0,3,0,0,0,0,1,0,...,0,0,0,3,0,0,0,1,0,1.234540
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,-1.866593
2,2,1,2,3,1,3,0,3,0,0,...,2,0,2,3,2,0,0,2,3,-0.678925
3,2,2,2,0,0,0,0,0,3,2,...,0,3,0,0,0,0,0,3,0,0.244817
4,2,3,2,2,2,2,0,2,0,0,...,2,2,3,2,3,0,0,2,3,0.574725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2,1,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,-0.744907
362,3,2,1,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,2,0,-0.019109
363,3,2,2,2,3,2,0,2,0,0,...,3,0,3,0,3,0,0,2,3,-0.546962
364,2,1,3,1,2,3,0,2,0,0,...,3,0,2,0,1,0,0,2,3,0.904632
365,3,2,2,0,0,0,0,0,3,3,...,0,2,0,0,0,0,0,3,0,-0.085091

In [ ]:
x_train, x_test = x[0:300], x[301:]
y_train, y_test = y[0:300], y[301:]
x_train.shape

(300, 34)

## K is the number of distinct classes

In [ ]:
df.iloc[:,34].unique()
k = 6

*w* is a 6 X 34 matrix



```
`# This is formatted as code`
```

In [ ]:
w = np.random.normal(loc = 0.0, scale = 1.0, size = (6,34))

w.shape,x_train.shape

((6, 34), (300, 34))

In [ ]:
def hypothesis(x_train,w,i):
  h_theta_x  = np.zeros(6)
  for k in range(6):
    h_theta_x[k] += np.exp(np.dot(w[k], x_train.loc[i]))
  sum = np.sum(h_theta_x)
  return h_theta_x/sum

In [ ]:
x_train.loc[262]

erythema                               2.000000
scaling                                1.000000
definite_borders                       0.000000
itching                                2.000000
koebner_phenomenon                     0.000000
polygonal_papules                      0.000000
follicular_papules                     0.000000
oral_mucosal_involvement               0.000000
knee_and_elbow_involvement             0.000000
scalp_involvement                      0.000000
family_history                         0.000000
melanin_incontinence                   0.000000
eosinophils_infiltrate                 0.000000
PNL_infiltrate                         0.000000
fibrosis_papillary_dermis              2.000000
exocytosis                             1.000000
acanthosis                             3.000000
hyperkeratosis                         2.000000
parakeratosis                          2.000000
clubbing_rete_ridges                   1.000000
elongation_rete_ridges                 3.000000
thinning_suprapapillary_epidermis      0.000000
spongiform_pustule                     0.000000
munro_microabcess                      0.000000
focal_hypergranulosis                  0.000000
disappearance_granular_layer           0.000000
vacuolisation_damage_basal_layer       0.000000
spongiosis                             2.000000
saw_tooth_appearance_retes             0.000000
follicular_horn_plug                   0.000000
perifollicular_parakeratosis           0.000000
inflammatory_mononuclear_infiltrate    3.000000
band_like_infiltrate                   0.000000
age                                   -0.019109
Name: 262, dtype: float64

In [ ]:
h = hypothesis(x_train,w,0)
h

array([6.59650871e-05, 6.61410592e-02, 1.51871523e-02, 1.23074081e-05,
       5.07641234e-02, 8.67829393e-01])

In [ ]:
def log_likelihood(x_train,y_train,w):
  l_theta = 0
  indicator = lambda y,l: 1 if y == l else 0
  epsilon = 1e-15
  m,n = x_train.shape
  k = w.shape[0]
  for i in range(m):
    h_theta = hypothesis(x_train,w,i)
    for j in range(k):
      l_theta = l_theta + (np.log(h_theta[j] + epsilon )*indicator(y_train[i],j))
  return l_theta

In [ ]:
l = log_likelihood(x_train,y_train,w)
l

-2130.721234362631

In [ ]:
def derivative1(x_train,y_train,w):
  m,n = x_train.shape
  K = w.shape[0]
  indicator = lambda y,l: 1 if y == l else 0
  dl_dw = np.zeros((w.shape))
  for i in range(m):
    h_theta = hypothesis(x_train,w,i)
    for j in range(K):
      h_theta_j = h_theta[j]
      indic_y_J = indicator(y_train[i],j)
      for k in range(n):
        dl_dw[j,k] += (indic_y_J - h_theta_j)*x_train.iloc[i,k]
  return dl_dw

In [ ]:
der1= derivative1(x_train,y_train,w)
der1

array([[-4.16822203e+01, -3.58412843e+01, -2.79280451e+01,
        -1.22964226e+01, -8.02540646e+00, -4.47579224e-06,
        -1.62035253e+01, -4.57577760e-06, -1.29053880e+01,
        -6.92467903e+00, -4.21756408e+00, -3.86829090e-06,
        -1.49670138e+00, -8.65106610e+00, -5.95102429e+00,
        -2.31539344e+01, -3.44401050e+01, -7.61417177e+00,
        -2.00499800e+01, -4.51168556e+00, -1.46662414e+01,
        -6.08621780e+00, -4.82905607e+00, -3.49033138e+00,
        -3.25702719e-01, -2.30182824e-01, -2.80027105e-04,
        -1.82932466e+01, -2.46140997e-02, -1.14976668e+01,
        -1.47939025e+01, -3.13512440e+01, -1.16670436e-01,
         1.73736655e+01],
       [ 1.49197211e+02,  1.57638155e+02,  1.61092785e+02,
         4.62767897e+01,  3.65106256e+01, -1.76751710e+00,
         2.16202316e+00, -1.71153691e+00,  1.37767473e+02,
         1.31035750e+02,  2.62473669e+01, -1.33018166e-01,
         9.18078154e-01,  1.03762355e+02, -7.84963490e+00,
        -1.96197320e+01,  1.42772937e+02,  5.70365823e+01,
         1.51097588e+02,  1.70957664e+02,  1.79522205e+02,
         1.66195106e+02,  8.32245866e+01,  8.21580716e+01,
        -8.82258892e-02,  8.30611204e+01,  8.51985511e-01,
        -3.86640918e+01, -1.76057067e+00, -1.07861873e+00,
        -1.10720346e+00,  1.12148115e+02,  1.12714751e+00,
         8.13941178e+00],
       [-2.87284971e+00, -6.55480058e+00, -3.36772360e+01,
         1.79086064e+01, -9.20278148e+00, -2.78322015e+01,
        -1.09158360e+01, -2.36687845e+01, -3.09391245e+01,
        -1.70677642e+01, -3.92280990e+00, -2.39893402e+01,
         2.56863383e+00,  1.13773973e+01, -5.79022290e+00,
         3.10273989e+01, -1.65552408e+01, -9.34684314e+00,
        -5.26161036e+01, -3.19716127e+01, -4.55058082e+01,
        -2.46687710e+01, -2.03844971e+01, -8.23985884e+00,
        -2.69603044e+01, -1.16601890e+01, -2.88692499e+01,
         3.53739884e+01, -2.87255192e+01, -7.42959250e+00,
        -9.14472119e+00, -2.47009431e+01, -2.69870008e+01,
        -3.35148578e+00],
       [-5.47279014e+01, -7.72605506e+01, -4.31834009e+01,
         6.96937555e+01,  1.27624715e+01,  1.31868178e+02,
        -9.26195962e+00,  1.14875034e+02, -1.14646373e+02,
        -1.12287622e+02, -2.36659163e+01,  1.19885167e+02,
         6.54215796e+00, -8.43806332e+01,  3.88801341e+00,
         7.11828772e+01, -3.96637108e+01, -5.64507129e+01,
        -6.52052738e+01, -1.37035315e+02, -1.36820214e+02,
        -1.34700699e+02, -5.68301225e+01, -6.97860264e+01,
         1.15757498e+02, -6.69301387e+01,  1.34897093e+02,
         4.29180229e+01,  1.33901478e+02, -2.44209564e+00,
        -3.94970969e+00, -1.90738561e+01,  1.55563284e+02,
         1.37473089e+01],
       [ 1.32636144e+01,  1.36245545e+01,  2.15579975e+01,
        -3.46780550e+01,  3.67229567e+01, -3.23857927e-03,
        -2.29331671e-01, -2.25435629e-03, -1.79999706e-01,
        -1.67907996e+00, -1.21975207e+00, -2.97692610e-03,
        -4.23166726e+00, -2.10599547e+01, -1.01637836e+01,
         3.00646732e+01,  9.02277250e+00,  1.23979109e+01,
         5.93106660e+00, -6.72277853e-02, -9.80517633e+00,
        -7.04536096e-02, -1.77692763e+00,  9.59260447e-01,
        -4.28744783e-03,  1.08526561e+01, -3.31216069e-03,
         2.72217653e+01,  9.96430633e-01, -4.31658146e-02,
        -5.96611440e-02,  2.60272515e+01, -4.18598100e-03,
         1.31141842e+01],
       [-9.31778537e+01, -7.66060744e+01, -9.28621008e+01,
        -9.59046739e+01, -6.87678658e+01, -1.02265216e+02,
         4.48629391e-01, -8.94924540e+01, -5.09658814e+00,
        -3.07660493e+00, -1.22132460e+00, -9.57598280e+01,
        -4.30050130e+00, -4.04809857e+00,  2.58666523e+01,
        -1.08501283e+02, -8.31366532e+01, -1.00227654e+01,
        -4.11572971e+01,  6.28176871e-01,  2.52752356e+01,
        -6.68964739e-01, -4.03983296e-01, -1.60111545e+00,
        -8.93789777e+01, -1.50932659e+01, -1.06876237e+02,
        -6.35564381e+01, -1.04387205e+02, -5.08860490e-01,
        -9.44801989e-01, -8.60493236e+01, -1.30582574e+02,
        -2.24097991e+01]])

In [ ]:
def derivative(x_train,y_train,w):
  m,n = x_train.shape
  K = w.shape[0]
  indicator = lambda y,l: 1 if y == l else 0
  dl_dw = np.zeros((w.shape))
  for j in range(K):
    for k in range(n):
      der = 0
      for i in range(m):
        h_theta = hypothesis(x_train,w,i)
        der += (indicator(y_train[i],j) - h_theta[j])*x_train.iloc[i,k]
      dl_dw[j,k] = der
  return dl_dw

In [ ]:
der = derivative(x_train,y_train,w)

array([[-4.16822203e+01, -3.58412843e+01, -2.79280451e+01,
        -1.22964226e+01, -8.02540646e+00, -4.47579224e-06,
        -1.62035253e+01, -4.57577760e-06, -1.29053880e+01,
        -6.92467903e+00, -4.21756408e+00, -3.86829090e-06,
        -1.49670138e+00, -8.65106610e+00, -5.95102429e+00,
        -2.31539344e+01, -3.44401050e+01, -7.61417177e+00,
        -2.00499800e+01, -4.51168556e+00, -1.46662414e+01,
        -6.08621780e+00, -4.82905607e+00, -3.49033138e+00,
        -3.25702719e-01, -2.30182824e-01, -2.80027105e-04,
        -1.82932466e+01, -2.46140997e-02, -1.14976668e+01,
        -1.47939025e+01, -3.13512440e+01, -1.16670436e-01,
         1.73736655e+01],
       [ 1.49197211e+02,  1.57638155e+02,  1.61092785e+02,
         4.62767897e+01,  3.65106256e+01, -1.76751710e+00,
         2.16202316e+00, -1.71153691e+00,  1.37767473e+02,
         1.31035750e+02,  2.62473669e+01, -1.33018166e-01,
         9.18078154e-01,  1.03762355e+02, -7.84963490e+00,
        -1.96197320e+01,  1.42772937e+02,  5.70365823e+01,
         1.51097588e+02,  1.70957664e+02,  1.79522205e+02,
         1.66195106e+02,  8.32245866e+01,  8.21580716e+01,
        -8.82258892e-02,  8.30611204e+01,  8.51985511e-01,
        -3.86640918e+01, -1.76057067e+00, -1.07861873e+00,
        -1.10720346e+00,  1.12148115e+02,  1.12714751e+00,
         8.13941178e+00],
       [-2.87284971e+00, -6.55480058e+00, -3.36772360e+01,
         1.79086064e+01, -9.20278148e+00, -2.78322015e+01,
        -1.09158360e+01, -2.36687845e+01, -3.09391245e+01,
        -1.70677642e+01, -3.92280990e+00, -2.39893402e+01,
         2.56863383e+00,  1.13773973e+01, -5.79022290e+00,
         3.10273989e+01, -1.65552408e+01, -9.34684314e+00,
        -5.26161036e+01, -3.19716127e+01, -4.55058082e+01,
        -2.46687710e+01, -2.03844971e+01, -8.23985884e+00,
        -2.69603044e+01, -1.16601890e+01, -2.88692499e+01,
         3.53739884e+01, -2.87255192e+01, -7.42959250e+00,
        -9.14472119e+00, -2.47009431e+01, -2.69870008e+01,
        -3.35148578e+00],
       [-5.47279014e+01, -7.72605506e+01, -4.31834009e+01,
         6.96937555e+01,  1.27624715e+01,  1.31868178e+02,
        -9.26195962e+00,  1.14875034e+02, -1.14646373e+02,
        -1.12287622e+02, -2.36659163e+01,  1.19885167e+02,
         6.54215796e+00, -8.43806332e+01,  3.88801341e+00,
         7.11828772e+01, -3.96637108e+01, -5.64507129e+01,
        -6.52052738e+01, -1.37035315e+02, -1.36820214e+02,
        -1.34700699e+02, -5.68301225e+01, -6.97860264e+01,
         1.15757498e+02, -6.69301387e+01,  1.34897093e+02,
         4.29180229e+01,  1.33901478e+02, -2.44209564e+00,
        -3.94970969e+00, -1.90738561e+01,  1.55563284e+02,
         1.37473089e+01],
       [ 1.32636144e+01,  1.36245545e+01,  2.15579975e+01,
        -3.46780550e+01,  3.67229567e+01, -3.23857927e-03,
        -2.29331671e-01, -2.25435629e-03, -1.79999706e-01,
        -1.67907996e+00, -1.21975207e+00, -2.97692610e-03,
        -4.23166726e+00, -2.10599547e+01, -1.01637836e+01,
         3.00646732e+01,  9.02277250e+00,  1.23979109e+01,
         5.93106660e+00, -6.72277853e-02, -9.80517633e+00,
        -7.04536096e-02, -1.77692763e+00,  9.59260447e-01,
        -4.28744783e-03,  1.08526561e+01, -3.31216069e-03,
         2.72217653e+01,  9.96430633e-01, -4.31658146e-02,
        -5.96611440e-02,  2.60272515e+01, -4.18598100e-03,
         1.31141842e+01],
       [-9.31778537e+01, -7.66060744e+01, -9.28621008e+01,
        -9.59046739e+01, -6.87678658e+01, -1.02265216e+02,
         4.48629391e-01, -8.94924540e+01, -5.09658814e+00,
        -3.07660493e+00, -1.22132460e+00, -9.57598280e+01,
        -4.30050130e+00, -4.04809857e+00,  2.58666523e+01,
        -1.08501283e+02, -8.31366532e+01, -1.00227654e+01,
        -4.11572971e+01,  6.28176871e-01,  2.52752356e+01,
        -6.68964739e-01, -4.03983296e-01, -1.60111545e+00,
        -8.93789777e+01, -1.50932659e+01, -1.06876237e+02,
        -6.35564381e+01, -1.04387205e+02, -5.08860490e-01,
        -9.44801989e-01, -8.60493236e+01, -1.30582574e+02,
        -2.24097991e+01]])

In [ ]:
der.shape

(6, 34)

In [ ]:
x_train.shape,w.shape

((300, 34), (6, 34))

In [ ]:
import math

In [ ]:
def soft_max(x_train,y_train,w,alpha,no_iters):
  hist_log_likelihood =[]
  for i in range(no_iters):
    dL_dw = derivative1(x_train,y_train,w)
    w += alpha*dL_dw
    hist_log_likelihood.append(log_likelihood(x_train,y_train,w))
    if i % math.ceil(no_iters/10)== 0:
      print(f"{i}th iteration ::  log_likelihood : {hist_log_likelihood[-1]}")
  return w,hist_log_likelihood[-1]

In [ ]:
no_iters = 100
alpha = 0.005
w_updated = [[-8.76943330e+00, -5.45924509e+00, -3.42582414e+00,
        -1.24827965e+00, -1.15460300e+00,  2.85860960e-01,
        -7.12498857e+00,  1.22463116e+00, -7.70905733e+00,
        -3.43547093e+00, -1.56646819e+00, -9.33635130e-01,
        -5.20455785e-01, -7.36464463e-01, -1.13876052e+00,
        -4.97188115e+00, -6.24248157e+00, -1.49945511e+00,
        -6.01197376e+00, -8.56174157e-01,  1.05915251e+00,
        -1.64148500e-01,  1.14395153e-01, -7.23222090e-01,
         6.44707105e-03, -5.25184211e-01, -1.31494714e+00,
        -4.75315962e+00, -5.17241095e-02, -5.30500050e+00,
        -6.04899650e+00, -5.28895496e+00, -7.41515622e-01,
         6.03148448e+00],
       [-7.45655755e+00, -3.86690138e+00, -8.96963072e-01,
        -5.03046804e+00,  1.39173149e+00, -2.46003350e+00,
        -1.20649375e+01, -2.14652803e+00, -1.61757032e+00,
         1.82796466e+00, -1.63345674e+00, -2.19092539e+00,
        -2.00587870e+00,  2.56714920e+00, -5.68492321e+00,
        -1.10948988e+01, -6.85455910e+00, -3.29871227e+00,
        -1.05112948e+00,  8.93894462e+00,  5.21524777e+00,
         1.13528200e+01,  4.51788768e+00,  5.52303568e+00,
        -2.25458361e+00,  4.19678188e+00, -2.04702648e+00,
        -1.08021205e+01, -4.39430616e+00, -6.43576885e+00,
        -6.85407640e+00, -5.62293009e+00, -3.08279187e+00,
         8.97974689e+00],
       [-5.31504441e+00, -1.66546735e+00, -5.21466914e+00,
         3.59770890e+00, -1.28416163e+01, -6.07207587e+00,
        -9.34969472e+00, -3.83652126e+00, -7.71108471e+00,
        -2.71884796e+00, -3.67530491e+00, -2.81069529e+00,
         4.50851235e+00,  1.11371015e+01, -7.05000632e+00,
        -1.36793780e+00, -6.76449817e+00, -7.08909167e+00,
        -7.37867670e+00, -2.24623406e+00, -3.87403860e+00,
        -1.97748527e+00,  6.95992743e-01, -3.77787800e-02,
        -3.45380887e+00, -5.12121649e+00, -4.30069342e+00,
         1.23331266e+00, -7.00219488e+00, -7.02438904e+00,
        -1.04931985e+01, -9.62823255e+00, -6.26146661e+00,
         6.27239896e+00],
       [-1.01080426e+01, -8.13541574e+00, -4.23629289e-01,
         1.46147466e+00,  1.05138312e+00,  1.14598274e+01,
        -8.18046414e+00,  1.10846455e+01, -6.41069291e+00,
        -2.80872343e+00, -2.94699319e+00,  1.06494871e+01,
        -5.93085623e-01, -4.91628294e+00, -2.13290761e-01,
        -6.49905922e+00, -5.60551721e+00, -3.65810049e+00,
        -2.63327954e+00, -2.11092902e+00, -1.09690614e+00,
        -1.06062960e+00, -2.83471377e+00, -7.33213178e-03,
         1.12036134e+01,  4.40669095e-01,  1.14034016e+01,
        -8.65808974e+00,  1.02755124e+01, -5.98185029e+00,
        -6.85899297e+00, -2.98999628e+00,  1.25664449e+01,
         6.00334136e+00],
       [-8.19949593e+00, -8.07315882e+00, -4.83909574e+00,
        -1.05190593e+01,  1.14854803e+01, -4.94995247e+00,
        -6.31382833e+00, -3.46459850e+00, -1.12901946e+01,
        -7.45468305e+00, -5.12724485e+00, -3.02462024e+00,
        -4.82583552e-01, -8.40017987e+00, -1.64859539e+00,
         5.87235184e+00, -9.07109727e+00, -2.02376882e+00,
        -5.93191137e+00, -9.61504486e+00, -9.13094256e+00,
        -5.99078883e+00, -4.35278657e+00, -2.00718878e+00,
        -4.06195722e+00,  1.46572140e+00, -4.62541404e+00,
         2.79521434e+00, -3.72731506e+00, -4.62676864e+00,
        -8.95224083e+00, -5.11856935e+00, -5.40007110e+00,
         7.63101299e+00],
       [-9.40797683e+00, -7.96982013e+00, -5.01961815e+00,
         2.34288727e+00, -2.04501084e+00, -4.38583750e-01,
        -6.30223924e+00, -1.39852955e+00, -7.18776163e+00,
        -3.83035388e+00, -1.15016274e+00,  9.55688350e-01,
        -8.97366354e-01, -5.89949059e+00,  1.39848051e+01,
        -7.62878566e+00, -1.66571739e+00, -1.12521252e+00,
        -5.43714766e+00, -2.50397826e+00,  7.82138558e+00,
        -3.05816246e+00, -1.47207236e+00, -6.55971531e-01,
         3.20059233e-01, -1.98537702e+00,  5.74036110e-01,
        -8.05874405e+00, -3.06109355e+00, -4.96058675e+00,
        -7.22291282e+00, -2.11649273e+00, -1.44300150e+00,
         6.95230324e+00]]
w_updated = np.array(w_updated)
w_optimal,optimal_log_likelihoood = soft_max(x_train,y_train,w_updated,alpha,no_iters)
w_optimal

0th iteration ::  log_likelihood : -19.254398037291722
10th iteration ::  log_likelihood : -18.55979063387432
20th iteration ::  log_likelihood : -17.889121996271697
30th iteration ::  log_likelihood : -17.236695479595767
40th iteration ::  log_likelihood : -16.598387415640108
50th iteration ::  log_likelihood : -15.971335753997472
60th iteration ::  log_likelihood : -15.353575594504607
70th iteration ::  log_likelihood : -14.743766300477843
80th iteration ::  log_likelihood : -14.141053331770584
90th iteration ::  log_likelihood : -13.54506372528349

array([[-1.12754848e+01, -7.57457610e+00, -4.81946925e+00,
        -1.77543932e+00, -1.15460528e+00,  2.85860960e-01,
        -1.00083567e+01,  1.22463116e+00, -1.01956955e+01,
        -3.87287013e+00, -2.17940050e+00, -9.33635130e-01,
        -5.20455798e-01, -8.24896314e-01, -1.13876052e+00,
        -6.66119201e+00, -7.84896220e+00, -2.58253250e+00,
        -7.76298410e+00, -9.23624187e-01,  1.05818748e+00,
        -1.64148500e-01,  1.14202820e-01, -7.23222112e-01,
        -8.17893512e-02, -5.25186181e-01, -1.31494714e+00,
        -5.89220116e+00, -5.17241317e-02, -7.43786976e+00,
        -8.74014419e+00, -7.18930517e+00, -7.41517577e-01,
         8.18005086e+00],
       [-1.00358534e+01, -5.86681939e+00, -2.39634037e+00,
        -5.97664183e+00,  1.38828806e+00, -2.46003350e+00,
        -1.50128710e+01, -2.14652803e+00, -4.18937485e+00,
         3.90370543e-01, -2.38571199e+00, -2.19092539e+00,
        -2.00587870e+00,  2.16647887e+00, -5.68492322e+00,
        -1.25962509e+01, -8.50966283e+00, -4.69389422e+00,
        -2.87248910e+00,  8.45258190e+00,  4.71150241e+00,
         1.13522302e+01,  4.25874207e+00,  5.52131396e+00,
        -2.25458361e+00,  4.19677979e+00, -2.04702648e+00,
        -1.12930590e+01, -4.39602788e+00, -8.12634738e+00,
        -9.09531361e+00, -7.52471762e+00, -3.22259487e+00,
         1.13664556e+01],
       [-8.01051484e+00, -3.94388608e+00, -5.22797328e+00,
         2.56398066e+00, -1.27250922e+01, -6.07207587e+00,
        -1.20465301e+01, -3.83652126e+00, -9.23356100e+00,
        -3.30989564e+00, -4.87445180e+00, -2.81069529e+00,
         4.38014905e+00,  1.08585232e+01, -7.05000632e+00,
        -2.80042521e+00, -8.77491352e+00, -7.63687190e+00,
        -9.92381060e+00, -2.24636031e+00, -3.87212687e+00,
        -1.97689546e+00,  6.97172310e-01, -3.77787800e-02,
        -3.45470519e+00, -5.41428953e+00, -4.30069342e+00,
        -8.60249038e-01, -7.00219488e+00, -8.60524965e+00,
        -1.33508200e+01, -1.17305152e+01, -6.04865758e+00,
         7.93943294e+00],
       [-1.23463632e+01, -9.96212154e+00, -2.13529186e+00,
         5.41942023e-01,  1.03715647e+00,  1.14598274e+01,
        -1.12269078e+01,  1.10846455e+01, -9.27555428e+00,
        -4.00167012e+00, -3.24992964e+00,  1.06494871e+01,
        -5.93085801e-01, -5.55197024e+00, -2.13290771e-01,
        -8.15122159e+00, -7.47107424e+00, -4.89919531e+00,
        -4.50469650e+00, -2.23293408e+00, -1.09690718e+00,
        -1.06062960e+00, -2.83471453e+00, -1.44432852e-02,
         1.09335789e+01,  4.40662478e-01,  1.14034016e+01,
        -9.51081131e+00,  1.02684012e+01, -7.91667499e+00,
        -9.15839177e+00, -4.57333077e+00,  1.19934421e+01,
         8.06391932e+00],
       [-1.07606224e+01, -1.02744592e+01, -6.08030523e+00,
        -1.05763405e+01,  1.13866287e+01, -4.94995247e+00,
        -8.86871939e+00, -3.46459850e+00, -1.27485246e+01,
        -7.87117164e+00, -5.72412566e+00, -3.02462024e+00,
        -3.52503434e-01, -8.11413831e+00, -1.64859539e+00,
         4.02108556e+00, -1.09364320e+01, -3.02106437e+00,
        -6.94040843e+00, -9.61504516e+00, -9.13094256e+00,
        -5.99078883e+00, -4.35278657e+00, -1.99835589e+00,
        -4.06195722e+00,  1.75880514e+00, -4.62541404e+00,
         5.61259343e-01, -3.71848217e+00, -6.75318843e+00,
        -1.15051100e+01, -7.37487248e+00, -5.40007223e+00,
         1.03203917e+01],
       [-1.18277119e+01, -1.00481462e+01, -6.66041954e+00,
         1.32676279e+00, -2.04501100e+00, -4.38583750e-01,
        -9.17276745e+00, -1.39852955e+00, -9.28365127e+00,
        -4.75487761e+00, -1.68601103e+00,  9.55688350e-01,
        -8.99082980e-01, -6.28216437e+00,  1.39848051e+01,
        -9.00220665e+00, -3.66282596e+00, -2.86078258e+00,
        -7.43972978e+00, -2.82803390e+00,  7.32418528e+00,
        -3.05816246e+00, -1.71391322e+00, -6.55971531e-01,
         1.79226516e-01, -1.98537704e+00,  5.74036110e-01,
        -8.74852573e+00, -3.06109355e+00, -6.99503386e+00,
        -9.58063850e+00, -3.87243475e+00, -1.44300161e+00,
         9.30668019e+00]])

In [ ]:
i = 351
h = hypothesis(x_test,w_optimal,i)
h,h.argmax()

(array([4.63178263e-46, 1.00000000e+00, 5.87457661e-63, 4.21845930e-42,
        1.55689924e-85, 1.99518290e-44]),
 1)

In [ ]:
y_test.loc[351]

1

In [ ]:
count = 0
count_class6 = 0
false = 0
for i in range(0,366):
    h = hypothesis(x,w_optimal,i)
    actual = y.loc[i]
    if round(h.max()) == 1 :
      if actual == h.argmax():
        count += 1
      else:
        false += 1
    elif round(h.max()) != 1:
      count += 1
      count_class6 += 1
count

(347, 7, 19)

In [ ]:
347 + 7 + 19

373